### ISSUE TITLE
Add an "Apply Damage" button to the chatbox damage message

### ISSUE THREAD

**Issue by thurianknight** [thurianknight/hyp3e#21]
Similar to what OSE and Pathfinder 2E do, would be great to have one or more buttons for Apply Damage, Apply Healing, maybe Apply Double Damage (for crits) or Apply Half Damage (for saves that reduce damage by half). For weapons that can be used 1- or 2-handed, have a damage button for each.

**Comment by wintersleepAI** [comment]
Do you want help with this one? I have done it before.

**Comment by thurianknight** [comment]
> Do you want help with this one? I have done it before.

Go for it! I'm super busy this week and next, so I won't be able to touch it myself. I had been looking at how OSE does it, but that initial look at their code was as far as I got.

**Comment by thurianknight** [comment]
Completed via PR #38
