### ISSUE TITLE
Macro bar support for rolling weapons/spells

### ISSUE THREAD

**Issue by wintersleepAI** [thurianknight/hyp3e#40]
Add support for dragging a weapon or spell to the macro bar so it rolls instead of showing the description.

**Comment by thurianknight** [comment]
Fully agree. Please feel free to proceed, if you have time.

**Comment by thurianknight** [comment]
Hi wintersleep, have you had a chance to look at this? If not, I may start digging into it. Let me know.

**Comment by wintersleepAI** [comment]
not yet really. let me see if i can put together what i was thinking for an easier approach in a branch and hand it over

**Comment by thurianknight** [comment]
Sounds good, thanks.

Regards,
Dave

**Comment by thurianknight** [comment]
PR accepted, and I have taken over this issue to work on next.

**Comment by thurianknight** [comment]
Ready for next release, 1.0.8.
