### ISSUE TITLE
fighting ability roll button fails

### ISSUE THREAD

**Issue by wintersleepAI** [thurianknight/hyp3e#44]
this line `rollFormula = rollFormula.replace("@item.atkMod", item.system.atkMod)` is causing:

`TypeError: item is null
    rollAttackOrSpell http://localhost:30000/systems/hyp3e/module/documents/actor.mjs:471
    _onRoll http://localhost:30000/systems/hyp3e/module/sheets/actor-sheet.mjs:671
    jQuery 9
    activateListeners http://localhost:30000/systems/hyp3e/module/sheets/actor-sheet.mjs:286`

**Comment by thurianknight** [comment]
Fixed with commit 0081656.
