### ISSUE TITLE
Items do not retain their images when transferred to characters

### ISSUE THREAD

**Issue by arcos** [thurianknight/hyp3e#49]
Steps to reproduce:

1. Create an item in the Items tab
2. Give the item an image
3. Drag the item to a character
4. Notice that the item image reverts to the default SVG

This impacts the items displayed in the lists on the character sheet and the item detail view when launched from the character sheet.

![item-image-bug](https://github.com/user-attachments/assets/14bc49dc-88c4-4082-a0cc-296c6381e6ab)

![item-image-bug-02](https://github.com/user-attachments/assets/7db66e53-de94-480f-a04d-a5a3346874a3)

**Comment by thurianknight** [comment]
Confirmed bug. Will be fixed in next release.
