### ISSUE TITLE
default token settings for PCs

### ISSUE THREAD

**Issue by wintersleepAI** [thurianknight/hyp3e#52]
When a new character / PC is created set the token to be linked by default, vision enabled, and token disposition to be neutral.

**Comment by thurianknight** [comment]
Merged into dev branch.

**Comment by thurianknight** [comment]
Ready for release v1.0.5.

**Comment by thurianknight** [comment]
Just realized part of this is for PCs, which is not done yet. Re-opening issue.

**Comment by thurianknight** [comment]
Final items completed for next release, 1.0.8
