### ISSUE TITLE
HP Percent Bar not working in Foundry v11

### ISSUE THREAD

**Issue by thurianknight** [thurianknight/hyp3e#56]
It only shows 100% full.

**Comment by thurianknight** [comment]
Error in Math.clamp, this function was not implemented in Foundry v11. One line of code needs to be updated to replace this command with something that does effectively the same thing.

**Comment by thurianknight** [comment]
Code fixed, ready for release 1.0.4.

**Comment by wintersleepAI** [comment]
Doh! Sorry on that one!

**Comment by thurianknight** [comment]
Hey no worries! This was a good opportunity for me to study your code and
learn how it all works.

Regards,
Dave
